# By default Sylius uses urls like https://example.com/en_US/, but Sylius also offers the option to disable
# localized URLs (see https://docs.sylius.com/en/latest/cookbook/shop/disabling-localised-urls.html).
# To accommodate this in your plugin, provide a routes file for non localized stores and tell this in the README.md

asdoria_shipping_delivery_time_shop:
    resource: "routes/shop.yaml"

asdoria_shipping_delivery_time_admin:
    resource: "routes/admin.yaml"
    prefix: /admin
