imports:
    - { resource: 'ui.yaml' }

doctrine:
    orm:
        resolve_target_entities:
            Asdoria\Bundle\ShippingCountBundle\Model\ShippingScheduleInterface: Asdoria\Bundle\ShippingCountBundle\Entity\ShippingSchedule

framework:
    cache:
        pools:
            app.shipping_delivery_time_cache_pool:
                adapter: cache.app
